# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Genonbeta
email: genonbeta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Genonbeta is a small organization against the problems that 
  had always been solved the same way by providing unique tools
  and solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://genonbeta.github.io" # the base hostname & protocol for your site
twitter_username: genonbeta
github_username:  genonbeta

# Build settings
markdown: kramdown
